### ISSUE TITLE
安装openscep服务问题

### ISSUE THREAD

**Issue by anJava** [zhaozg/openscep#1]
你好！zhaozg
        我是一名上海刚工作的java开发者，我在linux上安装openscep时，make编译时报错，能不能请教一下这方面的问题，这是我的qq：870963566， 非常感谢！

**Comment by zhaozg** [comment]
1. 我不用QQ
2. 仔细阅读 https://github.com/zhaozg/openscep/blob/master/INSTALL
3. 把你碰到的问题(编译参数，编译日志)贴出来，问具体的问题比笼统提问更有效率

**Comment by anJava** [comment]
![qq 20160122173814](https://cloud.githubusercontent.com/assets/16832486/12507204/41c4d4fc-c12f-11e5-952e-1ff1841e030d.png)

就是make的时候，出错了

**Comment by zhaozg** [comment]
检查你的openssl 是否支持MD5算法，因为MD5算法被认为已经不安全，好多openssl已经不支持MD5算法了, 如果openssl已经启用MD5算法，这个肯定是过得去的，你参考 https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/md5/md5.h#L98

这个问题不复杂，您看看自己能不能搞定。

另外: 你在github或其他技术型论坛也好，博客也好，直接贴TEXT就可以了，上图的话，其他人不好从里面复制关键词，去搜索引擎帮我寻找，另外在手机上面看的话也需要流浪。

**Comment by anJava** [comment]
恩，好的，现在还是不行。
这是make后的打印信息：
[root@localhost openscep-0.4.2]# make
Making all in libltdl
make[1]: Entering directory `/usr/local/openscep-0.4.2/libltdl'
/bin/sh ./libtool --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I.     -g -O2 -c ltdl.c
./libtool: line 727: test: =: unary operator expected
gcc -DHAVE_CONFIG_H -I. -I. -I. -g -O2 -c ltdl.c -o ltdl.o
echo timestamp > ltdl.lo
/bin/sh ./libtool --mode=link gcc  -g -O2  -o libltdlc.la   ltdl.lo -ldl 
mkdir .libs
rm -fr .libs/libltdlc.la .libs/libltdlc.* .libs/libltdlc.*
ar cru .libs/libltdlc.a  ltdl.o 
ranlib .libs/libltdlc.a
creating libltdlc.la
(cd .libs && rm -f libltdlc.la && ln -s ../libltdlc.la libltdlc.la)
make[1]: Leaving directory`/usr/local/openscep-0.4.2/libltdl'
Making all in include
make[1]: Entering directory `/usr/local/openscep-0.4.2/include'
make[1]: Leaving directory`/usr/local/openscep-0.4.2/include'
Making all in openssl
make[1]: Entering directory `/usr/local/openscep-0.4.2/openssl'
sh ../config.sh <openscepsetup.in >openscepsetup
sh ../config.sh <openscep.cnf.in >openscep.cnf
make[1]: Leaving directory`/usr/local/openscep-0.4.2/openssl'
Making all in ldap
make[1]: Entering directory `/usr/local/openscep-0.4.2/ldap'
sh ../config.sh <openscep.ldif.in >openscep.ldif
make[1]: Leaving directory`/usr/local/openscep-0.4.2/ldap'
Making all in lib
make[1]: Entering directory `/usr/local/openscep-0.4.2/lib'
/bin/sh ../libtool --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../include -I../libltdl -I../include -I/usr/local/ssl/include  -DOPENSCEPDIR=\"/usr/local/lib/openscep\"  -g -O2 -c init.c
mkdir .libs
gcc -DHAVE_CONFIG_H -I. -I. -I../include -I../libltdl -I../include -I/usr/local/ssl/include -DOPENSCEPDIR=\"/usr/local/lib/openscep\" -g -O2 -c init.c  -fPIC -DPIC -o .libs/init.lo
In file included from ../include/init.h:13,
                 from init.c:9:
../include/scep.h:83: error: expected specifier-qualifier-list before 'LHASH'
init.c: In function 'scep_clear':
init.c:122: error: 'scep_t' has no member named 'check_transid'
init.c:123: error: 'scep_t' has no member named 'l'
init.c:124: error: 'scep_t' has no member named 'l'
init.c: In function 'scep_config':
init.c:136: error: 'scep_t' has no member named 'conf'
init.c:138: error: 'scep_t' has no member named 'conf'
init.c:145: error: 'scep_t' has no member named 'conf'
init.c:155: error: 'scep_t' has no member named 'conf'
init.c:161: error: 'scep_t' has no member named 'conf'
init.c:165: error: 'scep_t' has no member named 'cacert'
init.c:166: error: 'scep_t' has no member named 'cacert'
init.c:176: error: 'scep_t' has no member named 'conf'
init.c:180: error: 'scep_t' has no member named 'capkey'
init.c:181: error: 'scep_t' has no member named 'capkey'
init.c:191: error: 'scep_t' has no member named 'conf'
init.c:195: error: 'scep_t' has no member named 'crl'
init.c:196: error: 'scep_t' has no member named 'crl'
init.c:207: error: 'scep_t' has no member named 'l'
init.c:207: error: 'scep_t' has no member named 'conf'
init.c:208: error: 'scep_t' has no member named 'l'
init.c:208: error: 'scep_t' has no member named 'conf'
init.c:209: error: 'scep_t' has no member named 'l'
init.c:209: error: 'scep_t' has no member named 'conf'
init.c:210: error: 'scep_t' has no member named 'l'
init.c:210: error: 'scep_t' has no member named 'conf'
init.c:211: error: 'scep_t' has no member named 'l'
init.c:211: error: 'scep_t' has no member named 'conf'
init.c:215: error: 'scep_t' has no member named 'l'
init.c:215: error: 'scep_t' has no member named 'l'
init.c:216: error: 'scep_t' has no member named 'l'
init.c:216: error: 'scep_t' has no member named 'l'
init.c:217: error: 'scep_t' has no member named 'l'
init.c:217: error: 'scep_t' has no member named 'l'
init.c:218: error: 'scep_t' has no member named 'l'
init.c:218: error: 'scep_t' has no member named 'l'
init.c:221: error: 'scep_t' has no member named 'conf'
init.c:224: error: 'scep_t' has no member named 'automatic'
init.c:232: error: 'scep_t' has no member named 'conf'
init.c:236: error: 'scep_t' has no member named 'check_transid'
init.c:245: error: 'scep_t' has no member named 'conf'
init.c:247: error: 'scep_t' has no member named 'community'
init.c:250: error: 'scep_t' has no member named 'community'

是不是有什么配置，我在linux上装了apache，perl，openssl后，然后解压了openscep，只后进入openscep主目录，.configure---->make      可我下的openssl跟openscep之间没有做关联配置

**Comment by zhaozg** [comment]
根据： https://github.com/zhaozg/openscep/blob/master/include/scep.h#L20
LHASH 应该是openssl 1.0 之后增加的类型，是不是因为你用的openssl版本低呢, 找你们有经验的同事去搞定吧.

**Comment by anJava** [comment]
恩，好的，谢谢了！
